language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - secure: VydDF0hWytsswxggolRoAjOuYhW26XBXuG5zYrVUYVkHiF+wK3ZhuRV9V65xP0FNyLQqarLos6FJnMutBwzkpCCfVm0OJvzs+iqXt2PY5nyTbD2QeVdcFnpBvXpcMJ6u5FNq0+uP5zL0l5xYxMxzDUcqceVqWh8h049PtDv7RZc=

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - mkdir -p build/logs

script:
  - phpunit --verbose --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v